### ISSUE TITLE
(Optionally) require password for accessing recovery

### ISSUE THREAD

**Issue by rugk** [omnirom/android_bootable_recovery#113]
When FDE (full disk encryption) in Android is enabled TWRP requests the password before getting to the main screen. However you can circumvent entering the password by tapping on "Cancel" on the main screen.

It would be nice if this possibility could (optionally via a setting) be removed, so that unauthorized users cannot get into the recovery.

**Comment by JoJoDeveloping** [comment]
then again unauthorized users can remove that possibility in their branch and skip pin entering again.

**Comment by SebiderSushi** [comment]
For more information see: https://twrp.me/faq/securetwrp.html

From my experience (this problem is mentioned in the FAQ, too): There exist vendor tools for probably every Android device which are able to flash anything onto the device regardless of a locked bootloader or FDE or password protection. Many of them can be found somewhere on the internet like Odin for Samsung devices.
I myself have such a tool for my Android phone and it already came in handy to recover from a soft-brick where I had a locked bootloader and neither a booting OS nor a booting recovery - using the tool I was able to flash a working recovery without touching anything else.
