### ISSUE TITLE
Changing the data partition from ext4 to f2fs fails on OnePlus3 with TWRP 3.2.1-0

### ISSUE THREAD

**Issue by gossbill** [omnirom/android_bootable_recovery#210]
Trying to change the format of the data partition from ext4 to f2fs fails with the following error in the log.
Formatting data using mkfs.f2fs...
mkfs.f2fs: invalid option -- r
	Error: Unknown option ?

TWRP: version 3.2.1-0 from https://dl.twrp.me/oneplus3/twrp-3.2.1-0-oneplus3.img.html
Logs and subsequent discussion here:https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/recovery-official-twrp-touch-recovery-t3742894/post75870705

**Comment by nergdron** [comment]
just discovered this trying to wipe a oneplus 3. seems like just a scripting typo, hopefully should be an easy fix?

**Comment by ThEMarD** [comment]
Heyyo, the issue is indeed the reserved length at the end of the data in twrp.fstab and TWRP trying to use -r when mkfs.f2fs does not support -r

[HTML]I:Set page: 'wipe'
I:Set page: 'advancedwipe'
I:checkpartitionlist list '/data;'
I:checkpartitionlist part_path '/data'
I:Set page: 'checkpartitionlist'
I:getpartitiondetails list '/data;'
I:getpartitiondetails part_path '/data'
I:Set page: 'partitionoptions'
I:Set page: 'selectfilesystem'
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:operation_start: 'Change File System'
I:sending message to remove 65537
I:[MTP] mtppipe remove storage 65537
I:Message sent, remove storage ID: 65537
Formatting Data using mkfs.f2fs...
mkfs.f2fs: invalid option -- r
	Error: Unknown option ?

Usage: mkfs.f2fs [options] device [sectors]
[options]:
  -a heap-based allocation [default:0]
  -c [device path] up to 7 devices excepts meta device
  -d debug level [default:0]
  -e [extension list] e.g. "mp3,gif,mov"
  -f force overwrite the exist filesystem
  -l label
  -m support zoned block device [default:0]
  -o overprovision ratio [default:5]
  -O [feature list] e.g. "encrypt"
  -q quiet mode
  -s # of segments per section [default:1]
  -S sparse mode
  -t 0: nodiscard, 1: discard [default:1]
  -z # of sections per zone [default:1]
sectors: number of sectors. [default: determined by device size]
mkfs.f2fs -t 0 -r 16384 /dev/block/sda9 process ended with ERROR: 1
Unable to wipe Data.
Error changing file system.[/HTML]

But if I remove "length=-16384;" from twrp.fstab? I can format it to and from f2fs without issue... but now data encryption might not work... going to test that.

**Comment by ThEMarD** [comment]
@nvertigo yeah I forgot to report back but yes removing footer from twrp.fstab did indeed result in encryption not working.

I also forgot to mention that I have a LeEco Le Max 2. The issue does not just affect the OnePlus3 and 3t.

Here was what a fellow LeEco Le Max 2 user recommended as another fix and this does work
https://github.com/GalaticStryder/android_bootable_recovery/commit/fc8ababf69ac866b733462fc35983b5d4af91cee

(btw, nvertigo I love your build scripts! I use it all the time hehe)

**Comment by nvertigo** [comment]
Workaround: https://forum.xda-developers.com/oneplus-3t/development/rom-nlos-15-1-20180223-t3754855/post75688089#post75688089

(Thanx for your appriciation!)

**Comment by ThEMarD** [comment]
We are too late to get it in for TWRP-3.2.2-0 (darn) but after thinking about it more? I believe you are right and we should just restore -r as that is what was implemented before.

@nvertigo since you found it, do you want to cherry-pick that to 8.1?

**Comment by nvertigo** [comment]
I tried that already, but it won't compile (I have a lineage build tree - since my ip uplink is vodafone mobile with 20€ for each 5GB over 10 GB, I don't want to sync an omni tree... :( ).

With omni/android-8.1 (on external_f2fs-tools) + "-r"-patch (https://github.com/nvertigo/android_external_f2fs-tools/tree/android-8.1 ):
`
bootable/recovery/Android.mk: error: recovery (EXECUTABLES android-arm64) missing libf2fs (STATIC_LIBRARIES android-arm64)
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
bootable/recovery/Android.mk: error: recovery (EXECUTABLES android-arm64) missing libf2fs_fsck (STATIC_LIBRARIES android-arm64)
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
bootable/recovery/Android.mk: error: recovery (EXECUTABLES android-arm64) missing libf2fs_mkfs (STATIC_LIBRARIES android-arm64)
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/core/main.mk:732: error: exiting from previous errors.
19:21:53 ckati failed with: exit status 1
`

With lineage/neage-15.1 + "-r"-patch (https://github.com/nvertigo/android_external_f2fs-tools/commit/f6b4d8988f1a65ab4367ea0963ab4cc940d2cb7f ) I get:
`
[  1% 11/941] target  C: mkfs.f2fs <= external/f2fs-tools/mkfs/f2fs_format_main.c
FAILED: /mnt/export/data/src/los15/out/target/product/oneplus3/obj/EXECUTABLES/mkfs.f2fs_intermediates/mkfs/f2fs_format_main.o
/bin/bash -c "PWD=/proc/self/cwd /usr/bin/ccache prebuilts/clang/host/linux-x86/clang-4053586/bin/clang         -I device/oneplus/oneplus3/include -I external/f2fs-tools/include -I external/e2fsprogs/lib/ -I system/core/libsparse/include -I external/f2fs-tools -I /mnt/export/data/src/los15/out/target/product/oneplus3/obj/EXECUTABLES/mkfs.f2fs_intermediates -I /mnt/export/data/src/los15/out/target/product/oneplus3/gen/EXECUTABLES/mkfs.f2fs_intermediates -I libnativehelper/include_deprecated \$(cat /mnt/export/data/src/los15/out/target/product/oneplus3/obj/EXECUTABLES/mkfs.f2fs_intermediates/import_includes)  -I system/core/include -I system/media/audio/include -I hardware/libhardware/include -I hardware/libhardware_legacy/include -I hardware/ril/include -I libnativehelper/include -I frameworks/native/include -I frameworks/native/opengl/include -I frameworks/av/include -isystem /mnt/export/data/src/los15/out/target/product/oneplus3/obj/include -isystem bionic/libc/arch-arm64/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -c  -fno-exceptions -Wno-multichar -fno-strict-aliasing -fstack-protector-strong -ffunction-sections -fdata-sections -funwind-tables -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -Werror=pointer-to-int-cast -Werror=int-to-pointer-cast -Werror=implicit-function-declaration -DNDEBUG -O2 -g -Wstrict-aliasing=2 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -DNDEBUG -UDEBUG -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -fdebug-prefix-map=\$PWD/= -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -nostdlibinc -mcpu=kryo -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin   -std=gnu99    -DWITH_ANDROID -DF2FS_MAJOR_VERSION=1 -DF2FS_MINOR_VERSION=10 -DF2FS_TOOLS_VERSION=\\\"1.10.0\\\" -DF2FS_TOOLS_DATE=\\\"2018-01-30\\\" -Wall -Werror -Wno-format -Wno-macro-redefined -Wno-missing-field-initializers -Wno-pointer-arith -Wno-sign-compare -Wno-unused-function -fPIE -D_USING_LIBCXX   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type   -MD -MF /mnt/export/data/src/los15/out/target/product/oneplus3/obj/EXECUTABLES/mkfs.f2fs_intermediates/mkfs/f2fs_format_main.d -o /mnt/export/data/src/los15/out/target/product/oneplus3/obj/EXECUTABLES/mkfs.f2fs_intermediates/mkfs/f2fs_format_main.o external/f2fs-tools/mkfs/f2fs_format_main.c"
external/f2fs-tools/mkfs/f2fs_format_main.c:178:4: error: use of undeclared identifier 'config'
                        config.bytes_reserved = atoi(optarg);
                        ^
external/f2fs-tools/mkfs/f2fs_format_main.c:308:2: error: unterminated function-like macro invocation
        MSG(0, "\n\tF2FS-tools: mkfs.f2fs Ver: %s (%s) [modified by Motorola to reserve space]\n\n",
        ^
external/f2fs-tools/include/f2fs_fs.h:201:9: note: macro 'MSG' defined here
#define MSG(n, fmt, ...)                                                \
        ^
external/f2fs-tools/mkfs/f2fs_format_main.c:359:2: error: expected '}'
}
 ^
external/f2fs-tools/mkfs/f2fs_format_main.c:307:1: note: to match this '{'
{
^
external/f2fs-tools/mkfs/f2fs_format_main.c:306:14: error: unused parameter 'argc' [-Werror,-Wunused-parameter]
int main(int argc, char *argv[])
             ^
external/f2fs-tools/mkfs/f2fs_format_main.c:306:26: error: unused parameter 'argv' [-Werror,-Wunused-parameter]
int main(int argc, char *argv[])
                         ^
5 errors generated.
`

Trying the first in an omni tree is worth a shot, I hope... ;)

Sorry for not wanting to sync omni, and many thanx for your efforts on a really great recovery!

**Comment by giner** [comment]
Experiencing the same issue on mido.

**Comment by ThEMarD** [comment]
@nvertigo turns out we no longer need to define footer length as footer is added automatically, so any device on TWRP that has it can remove it
https://review.lineageos.org/#/c/LineageOS/android_device_xiaomi_msm8996-common/+/205188/

**Comment by nvertigo** [comment]
I see your point, but honoring your second comment, it's just not working: it breaks encryptability of f2fs completely. Have you tried again with different result?

**Comment by ThEMarD** [comment]
Hmm yeah it turns out LineageOS doesn't have that issue since it's using latest upstream f2fs tools... OmniROM/TWRP does not

**Comment by fgl27** [comment]
I build TWRP with this https://github.com/fgl27/motorola-external-f2fs-tools/commits/oreo-8.1.0
Last build was 3 days ago, I use Lineage 15.1 and TWRP 8.1.
But I'm not building for OP but to this device:

https://github.com/fgl27/device_motorola_quark/tree/TWRP_O#device-configuration-for-moto-maxx-quark

build just fine and -r works as expected.

Just in case this helps... :+1:

**Comment by ThEMarD** [comment]
nvertigo if you could please test this https://gerrit.omnirom.org/#/c/android_bootable_recovery/+/33021/

**Comment by nvertigo** [comment]
I havn't managed to setup a twrp build environment on los. so I can't build. To my knowledge the commit you've metioned is in the famous fix3 build from here: https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/recovery-official-twrp-touch-recovery-t3742894/post78332159#post78332159 .

As you can see from the thread (especially the extensive tests of BillGoss@xda here: https://forum.xda-developers.com/oneplus-3/oneplus-3--3t-cross-device-development/recovery-official-twrp-touch-recovery-t3742894/post78339714#post78339714 ), this ptch works flawlessly.

**Comment by gossbill** [comment]
Closing this issue as the fix has been merged into TWRP https://gerrit.omnirom.org/#/c/android_bootable_recovery/+/33021/
